### ISSUE TITLE
(Not a issue)

### ISSUE THREAD

**Issue by guimc233** [liulihaocai/Fluidity#10]
A interesting client 🤔

~~May be I can contribute some shitcode?~~
But I need to finish the high school entrance examination these days.😂

I'm still a shitcoder.😂

[IM](https://t.me/bakaxiluo) 

_~~(Chinese Grammer XD)~~_

**Comment by hax0r31337** [comment]
It's welcomed to contribute to this client 🤗, but I'd say this client is almost died, there's no GPU acceleration for Jetpack Compose which causing frame rate strike and even ghost feature bans on hypixel.

**Comment by guimc233** [comment]
😯WTF

**Comment by guimc233** [comment]
I'll try to improve it (thought I have some paid clients._(Vape, Novoline@wtf, Flux)_)
