### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by guimc233** [liulihaocai/Fluidity#6]
May use AGPL-3.0 instead of GPL-3.0.

**Comment by hax0r31337** [comment]
AGPL-3.0 have the compatibility between GPL-3.0, This means that software licensed under the AGPL can be combined with software licensed under the GPL in a single program. However, the AGPL has an additional requirement that if the software is used over a network, the source code must be made available to users. This requirement is not present in the GPL.

**Comment by guimc233** [comment]
> the AGPL has an additional requirement that if the software is used over a network, the source code must be made available to users. This requirement is not present in the GPL.

So I think should use AGPL-3.0 instead of GPL-3.0

**Comment by hax0r31337** [comment]
> > the AGPL has an additional requirement that if the software is used over a network, the source code must be made available to users. This requirement is not present in the GPL.
> 
> So I think should use AGPL-3.0 instead of GPL-3.0

But I think this software have no such ability to use over a network :thinking:

**Comment by guimc233** [comment]
🤔
